version: '3.7'
services:
    db:
        container_name: app-db
        image: mysql
        command: ["--default-authentication-plugin=mysql_native_password"]
        ports:
            - "3309:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - mysql-datavolume:/var/lib/mysql
        networks:
            - db
    php:
        container_name: app-php
        build: ./php
        ports:
            - "9000:9001"
        volumes:
            - ${WORK_DIR}:/var/www/app
        depends_on:
            - db
        networks:
            - db
            - php
    nginx:
        container_name: app-web
        build: ./nginx
        ports:
            - "80:80"
        depends_on: 
            - php
        networks:
            - php
        volumes:
            - ${WORK_DIR}:/var/www/app
            - ./logs/nginx:/var/log/nginx

networks:
    db:
    php:

volumes:
    mysql-datavolume:
