version: '3.7'
services:
    db:
        container_name: app-db
        image: mysql
        command: ["--default-authentication-plugin=mysql_native_password"]
        ports:
            - "3309:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - mysql-datavolume:/var/lib/mysql
        networks:
            - db

networks:
    db:

volumes:
    mysql-datavolume:
